### ISSUE TITLE
Parse error on field "GithubRunID" of type "uint": strconv.ParseUint

### ISSUE THREAD

**Issue by kukido** [buildpulse/buildpulse-action#4]
```
+ curl -fsSL --retry 3 --retry-connrefused --connect-timeout 5 https://get.buildpulse.io/test-reporter-linux-amd64
+ BUILDPULSE_ACCESS_KEY_ID=***
+ BUILDPULSE_SECRET_ACCESS_KEY=***
+ GITHUB_SHA=***
+ ./buildpulse-test-reporter submit reports/junit/junit.xml --account-id ***(https://github.com/***/***/actions/runs/4307353711/jobs/7512312454#step:17:50) --repository-id ***(https://github.com/***/***/actions/runs/4307353711/jobs/7512312454#step:17:52)1755 --repository-dir .
<buildpulse> Current version: BuildPulse Test Reporter 0.24.1 (linux 786ad17 go1.18.3)
<buildpulse> Initiating `submit`
<buildpulse> Received args: reports/junit/junit.xml --account-id *** --repository-id ***(https://github.com/getstep/sdk/actions/runs/4307353711/jobs/7512312454#step:17:54)*** --repository-dir .
<buildpulse> Using working directory: /runner/_work/***/***
<buildpulse> Looking for git repository at .
<buildpulse> Found git repository at .
<buildpulse> Gathering metadata to describe the build
<buildpulse> Detected build environment: github-actions
env: parse error on field "GithubRunID" of type "uint": strconv.ParseUint: parsing "4307353711" (https://github.com/***/***/actions/runs/4307353711/jobs/7512312454#step:17:55)711": value out of range
Error: Process completed with exit code 1.
```

**Comment by kukido** [comment]
It was fixed by the team.

**Comment by nandahkrishna** [comment]
We're still seeing this issue on some PRs: Homebrew/brew#15100, Homebrew/brew#15101 and Homebrew/brew#15102 for example. These happen to be non-fork PRs (from Dependabot and our CI bot), PRs from a fork don't seem to be facing this issue.
